Actualiza img base Alpinev3.18
SIU-Toba/docker-php pull request #24
Opened 2023-05-31 14:47 UTC by enfoqueNativo

Actualiza Alpine 3.18 por cuestiones de seguridad

2023-05-31 19:48 UTC, sergiovier commented on 8.1-alpine/Dockerfile
> +# RUN ln -s /usr/bin/php81 /usr/bin/php
Si el link simbólico ya no necesita ser actualizado (esta testeado?), eliminemos ambas líneas.

2023-05-31 19:48 UTC, sergiovier requested changes
mejoras

2023-06-01 16:08 UTC, enfoqueNativo commented on 8.1-alpine/Dockerfile
> +# RUN ln -s /usr/bin/php81 /usr/bin/php
Testeado localmente, parece funcionar correctamente

2023-06-01 16:42 UTC, sergiovier approved these changes

2023-06-01 17:14 UTC, merged